/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#d4e4fa",
        "inverse-surface": "#d4e4fa",
        "primary-fixed": "#b1ecff",
        error: "#ffb4ab",
        "on-error": "#690005",
        secondary: "#c5c0ff",
        "on-surface-variant": "#bbc9ce",
        "tertiary-fixed": "#6ffbbe",
        tertiary: "#6ffcbe",
        "on-secondary-container": "#b6b0ff",
        "primary-fixed-dim": "#29d8ff",
        "on-primary-fixed": "#001f27",
        "on-tertiary": "#003824",
        "on-primary-fixed-variant": "#004e5e",
        "inverse-on-surface": "#233143",
        "tertiary-fixed-dim": "#4edea3",
        "outline-variant": "#3c494d",
        "on-tertiary-fixed-variant": "#005236",
        "surface-bright": "#2c3a4c",
        "surface-container-highest": "#273647",
        "inverse-primary": "#00677c",
        outline: "#859398",
        "on-error-container": "#ffdad6",
        "secondary-container": "#3e23ce",
        "surface-tint": "#29d8ff",
        "on-secondary-fixed-variant": "#3b1fcb",
        "surface-variant": "#273647",
        "tertiary-container": "#4fdfa3",
        "on-tertiary-container": "#005f40",
        "surface-container": "#122131",
        "on-tertiary-fixed": "#002113",
        surface: "#051424",
        "surface-dim": "#051424",
        background: "#051424",
        "on-background": "#d4e4fa",
        "on-primary": "#003641",
        "surface-container-high": "#1c2b3c",
        "primary-container": "#29d8ff",
        primary: "#b1ecff",
        "on-secondary": "#2600a1",
        "on-primary-container": "#005b6d",
        "surface-container-lowest": "#010f1f",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#c5c0ff",
        "secondary-fixed": "#e4dfff",
        "surface-container-low": "#0d1c2d",
        "on-secondary-fixed": "#140067",
      },
      spacing: {
        gutter: "24px",
        xs: "8px",
        md: "24px",
        base: "4px",
        "container-max": "1280px",
        xl: "80px",
        lg: "48px",
        sm: "16px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
      },
    },
  },
  plugins: [],
}
